### ISSUE TITLE
MuJoCo version pinning?

### ISSUE THREAD

**Issue by yuvaltassa** [microsoft/MoCapAct#8] opened 2022-08-05 06:31 UTC
Hi folks,

I'm one of the MuJoCo developers. We read your note and are a bit puzzled by it:

> Note: All included policies (experts, multi-clip, etc.) will only work with MuJoCo 2.1.5 or earlier. MuJoCo 2.2.0 uses analytic derivatives in place of finite-difference derivatives to determine actuator forces, which effectively changes the transition function of the simulator. Accordingly, MoCapAct installs MuJoCo 2.1.5 and dm_control 1.0.2. The rollout datasets were also generated under MuJoCo 2.1.5.

As far as we know no such change had occurred between 2.1.5 and 2.2.0 (the subsequent release). We did add some analytical derivatives but they are only used by the (non default) implicit integrator. We'd be happy to help you diagnose the cause of the change that you are seeing. In this matter and any other question you might have, please feel free to contact us at [github.com/deepmind/mujoco](https://github.com/deepmind/mujoco). 

Cheers!

**Comment by nolanwagener** [comment] 2022-08-05 14:09
Hi Yuval, thank you for reaching out! We'd also be happy to work with you to resolve the issue. :)

Here are the steps needed to reproduce the issue.
First, create the environment (here, using conda) and install the package:
```bash
conda create -n MoCapAct pip python==3.8
conda activate MoCapAct
git clone https://github.com/microsoft/MoCapAct.git
cd MoCapAct
pip install -e .
```
This will install MuJoCo 2.1.5.

Then, download a clip expert and roll it out:
```bash
python mocapact/download_dataset.py -t experts -c CMU_016_22 -d ./data
python mocapact/clip_expert/evaluate.py --policy_root experts/CMU_016_22-0-82/eval_rsi/model --always_init_at_clip_start --device cpu --ghost_offset 1 --act_noise 0
```
You should see this in the GUI:

https://user-images.githubusercontent.com/3906204/183092984-14e01643-7dd6-4d55-882c-b4c911c77f07.mp4

Then, update to the MuJoCo 2.2.0 and roll out the expert again:
```bash
pip install dm_control==1.0.3 mujoco==2.2.0 protobuf==3.20.1
python mocapact/clip_expert/evaluate.py --policy_root experts/CMU_016_22-0-82/eval_rsi/model --always_init_at_clip_start --device cpu --ghost_offset 1 --act_noise 0
```
Now the GUI will show this:

https://user-images.githubusercontent.com/3906204/183094073-6e2b9900-c095-471e-9408-8fda32860802.mp4


We looked through the changelog for MuJoCo 2.2.0 and the only potentially relevant difference I noticed was: "Added analytic derivatives of smooth (unconstrained) dynamics forces, with respect to velocities: Actuation forces." I suppose it could be caused by a change in dm_control, like the protobuf update.

**Comment by yuvaltassa** [comment] 2022-08-05 14:34
Hi @nolanwagener, nice to meet you.

To clarify, are you rolling out open loop trajectories?

**Comment by nolanwagener** [comment] 2022-08-05 14:38
Rolling out the experts, which provide feedback.

**Comment by yuvaltassa** [comment] 2022-08-05 14:53
Using 2.1.5, can you apply small perturbations and show that it's actually stabilising? e.g if you add some `eps*randn()` noise to your expert controller, how small does eps need to be for it to not fall? 1e-3, 1e-6 or 1e-12?

**Comment by nolanwagener** [comment] 2022-08-05 15:34
Here's the output with action noise of 0.1 (i.e., `--act_noise 0.1`):

https://user-images.githubusercontent.com/3906204/183110985-384e1dbd-c91b-45de-bfe8-160aac016f52.mp4

We trained the experts with action noise of 0.1 a la the NPMP paper to be able to handle small perturbations. We have a preliminary version of the [paper on OpenReview](https://openreview.net/forum?id=sWOdnSkB0qu) if you want to see more details.

**Comment by saran-t** [comment] 2022-08-05 17:32
The culprit is https://github.com/deepmind/dm_control/commit/a6d753fda04642b926ada094b07f88a1ffac98b6 which added changed the way that observables were added to the base walker class, which in turn affected the CMU Humanoid model. I'll double check internally whether this is something we actually wanted.

**Comment by saran-t** [comment] 2022-08-07 14:06
I believe this issue is now resolved in https://github.com/deepmind/dm_control/commit/f4e5e2336991017361f563db7e676fd08857076f.

If you have a minute to verify that from your end that would be much appreciated. Thanks!

**Comment by nolanwagener** [comment] 2022-08-08 00:16
@saran-t It works!

https://user-images.githubusercontent.com/3906204/183316842-92fe63c7-76fe-4933-afea-97298e926586.mp4

Thank you so much for addressing this! I'd be happy to remove the version pinning and disclaimer I had up before. Will you all be releasing a new version of dm_control with this fix soon?

**Comment by saran-t** [comment] 2022-08-08 00:46
Yes, this fix will go into our 1.0.6 release.

We'll let you know when 1.0.6 is ready, but until that happens it's probably a good idea for you to continue to recommend that people stick to 1.0.2, since that's the last easily installable version that works with your trained controllers.

If you don't mind removing the comment that the breakage is due to analytical derivatives, though, that'd be much appreciated. Thanks!

Sorry again for the breakage!

**Comment by nolanwagener** [comment] 2022-08-08 00:49
Will do. Cheers!

**Closed by nolanwagener** 2022-08-08 00:49 UTC

**Comment by saran-t** [comment] 2022-09-07 14:02
Could you please double check if the rendering problem goes away in version 1.0.5 (I want to rule out transient issues).

**Comment by nolanwagener** [comment] 2022-09-07 14:23
Here it is on 1.0.5.


https://user-images.githubusercontent.com/3906204/188902680-258637da-e17e-4998-8582-042106efe698.mp4

**Comment by saran-t** [comment] 2022-09-07 16:12
Confirmed reproducible on my MacBook.

**Comment by saran-t** [comment] 2022-09-07 17:09
Should be fixed in https://github.com/deepmind/dm_control/commit/d05e627a1917d658ff14d4d52006c133125dbaaa

Working on releasing it as 1.0.7 now.

**Comment by saran-t** [comment] 2022-09-07 17:27
OK, you should be good to go now :)
